import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { addFreezerMonths, arrangeFreezerLabelsForPositions, expandFreezerLabelQueue, normalizeFreezerLabelState, paginateFreezerLabels } from "../src/utils/freezerLabels.js";

assert.equal(addFreezerMonths("2026-09-08", 3), "2026-12-08");
assert.equal(addFreezerMonths("2026-11-30", 3), "2027-03-02");
assert.equal(normalizeFreezerLabelState({ layout: "bad", queue: "bad" }).layout, "portrait");
const expanded = expandFreezerLabelQueue([{ id: "one", name: "Soup", copies: 3 }]);
assert.equal(expanded.length, 3);
assert.equal(paginateFreezerLabels(Array(21).fill({})).length, 3);
const positioned = arrangeFreezerLabelsForPositions([{ id: "a" }, { id: "b" }], [2, 5]);
assert.equal(positioned[0].length, 10);
assert.equal(positioned[0][0], null);
assert.equal(positioned[0][1].id, "a");
assert.equal(positioned[0][4].id, "b");
const maker = readFileSync(new URL("../src/components/FreezerLabelMaker.jsx", import.meta.url), "utf8");
assert.match(maker, /Complete Dinners/);
assert.match(maker, /Healthy Dinners/);
assert.match(maker, /Build-a-Meals/);
assert.match(maker, /Bulk Items/);
assert.match(maker, /Favorites/);
assert.match(maker, /IMAGE_KINDS.*complete.*healthy.*build/);
assert.doesNotMatch(maker, /IMAGE_KINDS.*favorites/);
assert.match(maker, /getDietMealCalories/);
assert.match(maker, /getRecipeNutrition/);
assert.match(maker, /Nutrition Facts/);
assert.match(maker, /1 serving/);
assert.match(maker, /fittedLabelTextClass/);
const css = readFileSync(new URL("../src/components/FreezerLabelMaker.css", import.meta.url), "utf8");
assert.match(css, /place-content:center/);
assert.match(css, /width:8\.5in!important/);
assert.match(css, /width:4in;height:2in/);
assert.match(css, /left:\.25in;right:\.25in;bottom:\.25in/);
assert.match(css, /grid-template-rows:repeat\(5,2in\)/);
assert.match(css, /freezerLabelPositionGrid/);
assert.match(css, /freezerLabelTitleExtraLong/);
assert.match(css, /freezerImageLabelDate/);
assert.match(css, /font:600 5\.5pt\/1/);
assert.doesNotMatch(css.match(/\.freezerImageLabel h3\{[^}]+\}/)?.[0] || "", /text-overflow:ellipsis/);
const app = readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
assert.match(app, /FREEZER LABEL MAKER/);
assert.match(app, /activePage === "Freezer Label Maker"/);
assert.match(app, /PRINT LABELS/);
assert.match(app, /rrb:open-freezer-label/);
console.log("Freezer Label Maker v98.2 tests passed.");
