import assert from 'node:assert/strict';
import { newItem, readTransfer, cleanTransferItems, mergeCaptureInventory, TRANSFER_TYPE } from '../src/utils/inventoryCapture.js';
const a = {...newItem('Chicken broth'), quantity:'3', unit:'cans', notes:'Low sodium'};
assert.throws(()=>cleanTransferItems([{...a, quantity:'-1'}]));
assert.throws(()=>cleanTransferItems([{...a, quantity:'abc'}]));
assert.throws(()=>cleanTransferItems([a,a]));
assert.throws(()=>readTransfer({type:'wrong',version:1,items:[a]}));
const items = readTransfer({type:TRANSFER_TYPE,version:1,items:[a]});
let inventory = mergeCaptureInventory({records:{unrelated:{have:'5'}},customItems:[]},items);
const id=inventory.customItems[0].id;
assert.equal(inventory.records[id].have,'3');
assert.equal(inventory.records[id].notes,'Low sodium');
assert.equal(inventory.records.unrelated.have,'5');
assert.deepEqual(mergeCaptureInventory(inventory,items),inventory,'repeat import is idempotent');
inventory=mergeCaptureInventory(inventory,[{...newItem('Chicken broth'),quantity:'2',unit:'cans',action:'add'}]);
assert.equal(inventory.records[id].have,'5');
assert.equal(inventory.customItems.length,1);
inventory=mergeCaptureInventory(inventory,[{...newItem('Chicken broth'),quantity:'1',unit:'cans'}]);
assert.equal(inventory.records[id].have,'1');
inventory=mergeCaptureInventory(inventory,[{...newItem('Chicken broth','refrigerator'),quantity:'2',unit:'cans'}]);
assert.equal(inventory.customItems.length,2,'different location is a separate product');
const old=readTransfer({type:TRANSFER_TYPE,version:1,items:[{name:'Rice',destination:'pantry',quantity:'1'}]});
assert.equal(old[0].unit,'item');
console.log('Capture transfer validation, merge, quantities, location and repeat-import tests passed.');
