import assert from 'node:assert/strict';
import { newItem, readTransfer, cleanTransferItems, mergeCaptureInventory, inventorySnapshot, transferPayload, TRANSFER_TYPE } from '../src/utils/inventoryCapture.js';
const a={...newItem('Chicken broth'),brand:'Great Value',retailer:'Walmart',packageSize:'32 fl oz',quantity:'3',unit:'cartons',notes:'Low sodium'};
assert.equal(newItem().quantity,'1');
assert.throws(()=>cleanTransferItems([{...a,quantity:'-1'}]));
assert.throws(()=>cleanTransferItems([{...a,quantity:'abc'}]));
assert.throws(()=>cleanTransferItems([a,a]));
assert.throws(()=>readTransfer({type:'wrong',version:2,items:[a]}));
let inventory=mergeCaptureInventory({records:{unrelated:{have:'5',productName:'Eggs',unit:'cartons'}},customItems:[]},[a]);
const id=inventory.customItems[0].id;
for(const field of ['brand','retailer','packageSize','notes'])assert.equal(inventory.records[id][field],a[field]);
assert.equal(inventory.records[id].have,'3');
assert.equal(inventory.records.unrelated.have,'5');
assert.deepEqual(mergeCaptureInventory(inventory,[a]),inventory,'repeat import cannot add purchases twice');
const purchase={...newItem('Chicken broth'),brand:'Great Value',retailer:'Walmart',packageSize:'32 fl oz',quantity:'2',unit:'cartons'};
inventory=mergeCaptureInventory(inventory,[purchase]);
assert.equal(inventory.records[id].have,'5');assert.equal(inventory.customItems.length,1);
const snapshot=readTransfer(transferPayload(inventorySnapshot(inventory),'inventory'));
const edit=snapshot.find(item=>item.inventoryId===id);
const changed={...edit,id:newItem().id,name:'Chicken Broth — Less Sodium',brand:'Updated Brand',retailer:'H-E-B',packageSize:'48 fl oz',quantity:'1',destination:'refrigerator',storage:''};
inventory=mergeCaptureInventory(inventory,[changed]);
assert.equal(inventory.records[id].productName,changed.name);assert.equal(inventory.records[id].have,'1');
assert.equal(inventory.records[id].storage,'Refrigerator');assert.equal(inventory.customItems.length,1,'stable ID survives all product-detail edits');
inventory=mergeCaptureInventory(inventory,[{...changed,id:newItem().id,quantity:'0'}]);
assert.equal(inventory.records[id].stockStatus,'out');assert.equal(inventory.records[id].have,'0');
inventory=mergeCaptureInventory(inventory,[{...purchase,id:newItem().id,inventoryId:newItem().inventoryId,brand:'Swanson'}]);
assert.equal(inventory.customItems.length,2,'different brands do not combine');
const legacy=readTransfer({type:TRANSFER_TYPE,version:1,items:[{id:'old-item',name:'Rice',destination:'pantry',quantity:'1',unit:'bags'}]});
assert.equal(legacy[0].action,'replace');assert.equal(legacy[0].unit,'bags');
assert.equal(cleanTransferItems([{...a,photo:'data:image/jpeg;base64,YWJj'}])[0].photo,'data:image/jpeg;base64,YWJj');
assert.throws(()=>cleanTransferItems([{...a,photo:'javascript:alert(1)'}]));
console.log('Pocket Pantry fields, stable IDs, snapshots, purchases, zero-stock, repeat-import and legacy tests passed.');
