import assert from "node:assert/strict";
import fs from "node:fs";

const css = fs.readFileSync(new URL("../src/components/BuildYourOwnMealPage.css", import.meta.url), "utf8");
const jsx = fs.readFileSync(new URL("../src/components/BuildYourOwnMealPage.jsx", import.meta.url), "utf8");

assert.match(css, /\.mealBuilderWorkspaceGrid\s*\{[^}]*grid-template-columns:\s*minmax\(0,\.76fr\) minmax\(0,1fr\)[^}]*column-gap:\s*58px/);
assert.match(css, /\.mealBuilderWorkspaceGrid\s*\{[^}]*--meal-builder-selector-depth:[^;]*calc\(\(var\(--meal-builder-card-depth\) \* 2\) \+ 9px\)[^}]*align-items:\s*start/);
assert.match(css, /\.mealBuilderSelectorColumns\s*\{[^}]*grid-template-columns:\s*repeat\(3,minmax\(0,1fr\)\)/);
assert.match(css, /\.mealBuilderChoiceRail\s*\{[^}]*overflow-y:\s*auto[^}]*flex-direction:\s*column[^}]*overscroll-behavior-y:\s*contain[^}]*scroll-snap-type:\s*y mandatory/);
assert.match(css, /\.mealBuilderChoiceRail\s*\{[^}]*height:\s*var\(--meal-builder-selector-depth\)[^}]*max-height:\s*var\(--meal-builder-selector-depth\)/);
assert.match(css, /\.mealBuilderChoiceCard\s*\{[^}]*flex:\s*0 0 var\(--meal-builder-card-depth\)[^}]*height:\s*var\(--meal-builder-card-depth\)/);
assert.match(css, /\.mealBuilderChoiceCard\s*\{[^}]*scroll-snap-align:\s*start/);
assert.match(css, /\.mealBuilderMealSummaryCard\s*\{[^}]*overflow:\s*hidden[^}]*min-height:\s*96px/);
assert.match(css, /\.mealBuilderChoiceRail::-webkit-scrollbar-thumb/);
assert.doesNotMatch(jsx, /if \(a\.id === selectedId\) return -1;/);
assert.match(jsx, /categoryDifference \|\| normalizeRecipeTitle\(a\)\.localeCompare\(normalizeRecipeTitle\(b\)\)/);
assert.doesNotMatch(jsx, /scrollTo\(\{ top: 0, behavior: "smooth" \}\)/);
assert.match(jsx, /scrollBy\(\{ top: direction \* Math\.max/);
assert.doesNotMatch(jsx, />Dish Selectors</);
assert.doesNotMatch(jsx, /mealBuilderSelectorsHeading/);
assert.match(jsx, /mealBuilderWorkspaceGrid[\s\S]*mealBuilderPreviewColumn[\s\S]*mealBuilderDishSelectors/);
assert.doesNotMatch(jsx, />Calorie Overview</);
assert.doesNotMatch(jsx, /MealNutritionLine/);
assert.match(jsx, /placeholder="FILTER"/);
assert.match(jsx, /<span>Portion<\/span>/);
assert.match(jsx, />PRINT MEAL LABELS</);
assert.match(jsx, />CLEAR &amp; START OVER</);
assert.match(css, /\.mealBuilderTray\s*\{[^}]*aspect-ratio:\s*1448\/1086/);
assert.match(css, /\.mealBuilderPreviewColumn \.mealBuilderTrayPrimary\s*\{[^}]*aspect-ratio:\s*1448\/1086/);
assert.match(css, /\.mealBuilderChoiceLead input\[type="search"\][^}]*text-align:\s*center/);
assert.match(css, /\.mealBuilderPortionGrid label > span,[\s\S]*?text-align:\s*center/);
assert.match(jsx, /categoryLabel="Sort by Cuisine"/);
assert.match(jsx, /categoryLabel="Sort by Type"/);
assert.match(jsx, /categoryCode\(recipe\) === categoryFilter/);
assert.match(jsx, /const SIDE_CATEGORIES = \[\["SD", "Side Dishes"\]\]/);
assert.doesNotMatch(jsx, /\["SB", "Salads"\]/);
assert.doesNotMatch(jsx, /\["LF", "Breads & Rolls"\]/);
for (const category of ["AM", "AS", "HB", "IT", "MX", "SF", "SG", "CP"]) assert.match(jsx, new RegExp(`\\["${category}",`));
for (const category of ["CS", "DM", "HBP", "QP", "SW"]) assert.doesNotMatch(jsx.slice(0, jsx.indexOf("const MEAL_BUILDER_MAIN_IDS")), new RegExp(`\\["${category}",`));
assert.match(jsx, /mealBuilderSelectedDish/);
assert.match(css, /\.mealBuilderSelectedDish\s*\{[^}]*aspect-ratio:\s*16\/9/);
assert.match(css, /\.mealBuilderTrayFood\.is-empty\s*\{[^}]*top:\s*21\.0866%[^}]*height:\s*57\.6427%/);
assert.match(jsx, /className="mealBuilderSelectedDish has-selection" onClick=\{\(\) => onSelect\(""\)\}/);
assert.match(css, /\.buildYourOwnMealIntro p \+ p\s*\{[^}]*margin-top:\s*0/);
assert.doesNotMatch(css, /\.mealBuilderWorkspaceGrid\s*\{[^}]*grid-template-columns:\s*1fr\s*;/);

console.log("Meal Builder two-column vertical selector-reel contract passed");
