import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const component=readFileSync(new URL('../src/components/PhotoInventoryTransfer.jsx',import.meta.url),'utf8');
const app=readFileSync(new URL('../src/App.jsx',import.meta.url),'utf8');
const css=readFileSync(new URL('../src/components/PhotoInventoryTransfer.css',import.meta.url),'utf8');
for(const label of ['Store','Brand','Product name','Package size','Quantity','Storage location','Save & Add Another','Send Changes to RRB','Open My Inventory / Import File','Add to My Inventory on This Device'])assert.ok(component.includes(label),label);
assert.ok(component.includes('Optional reference photo'));
assert.ok(!/scanBarcode|readPhotoText|Read Text|Photograph Barcode/.test(component));
assert.ok(component.includes('navigator.share'));assert.ok(component.includes('setMasterInventory'));
assert.ok(app.includes('Open Pocket Pantry'));assert.ok(app.includes('Import / Export'));
assert.ok(css.includes('@media(max-width:480px)'));
console.log('Pocket Pantry product form and transfer UI contracts passed.');
