import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const [app, styles] = await Promise.all([readFile(new URL("../src/App.jsx", import.meta.url), "utf8"), readFile(new URL("../src/App.css", import.meta.url), "utf8")]);
const finalStart = styles.lastIndexOf("v97.11 — full-width four-action Shopping List control strip");
assert.ok(finalStart >= 0);
const finalStyles = styles.slice(finalStart);
assert.match(finalStyles, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\) !important/);
assert.match(finalStyles, /min-height: 40px !important;[\s\S]*height: 40px !important/);
assert.match(finalStyles, /white-space: nowrap !important/);
const actions = app.slice(app.indexOf('<div className="shoppingListIntroActions">'), app.indexOf("{showShoppingCompanion &&", app.indexOf('<div className="shoppingListIntroActions">')));
for (const label of ["Consolidated Shopping List", "Shopping List By Meal Component", "Print Your List", "Clear Meals &amp; Start Over"]) assert.match(actions, new RegExp(label));
assert.match(actions, /onClick=\{printShoppingList\}/);
assert.match(actions, /onClick=\{clearShoppingListAndStartOver\}/);
console.log("Current Shopping List command-strip contracts passed.");
