import { useEffect, useMemo, useState } from "react";
import { FREEZER_LABEL_LAYOUTS, FREEZER_LABEL_POSITIONS, FREEZER_LABEL_STORAGE_KEY, addFreezerMonths, arrangeFreezerLabelsForPositions, expandFreezerLabelQueue, formatFreezerLabelDate, localFreezerLabelDate, normalizeFreezerLabelState } from "../utils/freezerLabels.js";
import "./FreezerLabelMaker.css";

const IMAGE_KINDS = new Set(["complete", "healthy", "build"]);
const KINDS = [["complete", "Complete Dinners"], ["healthy", "Healthy Dinners"], ["build", "Build-a-Meals"], ["bulk", "Bulk Items"], ["favorites", "Favorites"]];
function emptyForm() { const frozenDate = localFreezerLabelDate(); return { kind: "complete", sourceId: "", name: "", subtitle: "", image: "", nutrition: {}, calories: "—", mealBalance: "—", frozenDate, useByDate: addFreezerMonths(frozenDate, 3), amount: "1 serving", instructions: "", notes: "", copies: 1 }; }
function loadState() { try { return normalizeFreezerLabelState(JSON.parse(localStorage.getItem(FREEZER_LABEL_STORAGE_KEY) || "{}")); } catch { return normalizeFreezerLabelState({}); } }
function titleParts(title = "", subtitle = "") { if (subtitle) return { title, subtitle }; const parts = String(title).split(/\s+with\s+/i); return parts.length > 1 ? { title: parts.shift(), subtitle: `With ${parts.join(" with ")}` } : { title, subtitle: "" }; }
function dinnerTitle(meal, recipeMap) { if (meal.title) return meal.title; return recipeMap.get(String(meal.mainRecipeId || "").toLowerCase())?.title || meal.rfisId || meal.id || "Complete Dinner"; }
function caloriesFor(item) { return item?.totalCalories ?? item?.calories ?? item?.nutrition?.calories ?? "—"; }
function mealBalanceFor(item) { return item?.mealBalance?.score ?? item?.mealBalance ?? "—"; }
function numericNutrient(value) { const parsed = Number.parseFloat(String(value ?? "").replace(/,/g, "")); return Number.isFinite(parsed) ? parsed : null; }
function nutritionFor(item = {}) { return { calories: item.calories ?? item.totalCalories ?? "—", protein: item.protein ?? "—", carbs: item.totalCarbohydrate ?? item.carbs ?? item.carbohydrates ?? "—", fat: item.totalFat ?? item.fat ?? "—", sodium: item.sodium ?? "—" }; }
function combineNutrition(items = []) { const keys = ["calories", "protein", "carbs", "fat", "sodium"]; return Object.fromEntries(keys.map((key) => { const values = items.map((item) => numericNutrient(item?.[key])).filter((value) => value !== null); return [key, values.length ? Math.round(values.reduce((sum, value) => sum + value, 0) * 10) / 10 : "—"]; })); }
function displayNutrient(value, unit = "") { if (value === null || value === undefined || value === "" || value === "—") return "—"; return /[a-z]/i.test(String(value)) ? value : `${value}${unit}`; }

function PrintableLabel({ label }) {
  if (label.labelStyle === "image" || IMAGE_KINDS.has(label.kind)) { const facts = nutritionFor(label.nutrition || { calories: label.calories }); const subtitle = label.subtitle || "With —"; return <article className="freezerPrintableLabel freezerImageLabel"><div className="freezerImageLabelTop">{label.image ? <img src={label.image} alt="" /> : <div className="freezerImagePlaceholder">Meal image</div>}<div className="freezerImageLabelCopy"><h3>{label.name}</h3><p className="freezerLabelSubtitle">{subtitle}</p><p className="freezerImageLabelDate">Frozen {formatFreezerLabelDate(label.frozenDate)}</p><p className="freezerImageLabelDate">Use by {formatFreezerLabelDate(label.useByDate)}</p></div></div><section className="freezerNutritionFacts"><header><strong>Nutrition Facts</strong><span>1 serving</span></header><div className="freezerNutritionValues"><span><small>Calories</small><b>{displayNutrient(facts.calories)}</b></span><span><small>Protein</small><b>{displayNutrient(facts.protein, "g")}</b></span><span><small>Carbs</small><b>{displayNutrient(facts.carbs, "g")}</b></span><span><small>Fat</small><b>{displayNutrient(facts.fat, "g")}</b></span><span><small>Sodium</small><b>{displayNutrient(facts.sodium, "mg")}</b></span></div></section></article>; }
  return <article className="freezerPrintableLabel freezerTextLabel"><h3>{label.name}</h3><div className="freezerLabelFacts"><span><small>FROZEN</small><strong>{formatFreezerLabelDate(label.frozenDate)}</strong></span><span><small>USE BY</small><strong>{formatFreezerLabelDate(label.useByDate)}</strong></span><span><small>AMOUNT</small><strong>{label.amount || "—"}</strong></span></div>{label.instructions && <p><strong>PREP:</strong> {label.instructions}</p>}{label.notes && <p><strong>NOTE:</strong> {label.notes}</p>}</article>;
}

export default function FreezerLabelMaker({ recipes = [], completeMeals = [], favorites = [], savedCustomMeals = [], getRecipeHeroImage = () => "", getCompleteMealHeroImage = () => "", getDietMealCalories = () => null, getRecipeNutrition = () => ({}), requestedRecipeId = "", onRequestedRecipeHandled = () => {} }) {
  const [saved, setSaved] = useState(loadState), [form, setForm] = useState(emptyForm), [search, setSearch] = useState(""), [showPreview, setShowPreview] = useState(false);
  const recipeMap = useMemo(() => new Map(recipes.map((recipe) => [String(recipe.id).toLowerCase(), recipe])), [recipes]);
  const sourceGroups = useMemo(() => {
    const recipeSource = (recipe, group) => { const parts = titleParts(recipe.title); const dietCalories = String(recipe.id || "").toUpperCase().startsWith("DM-") ? getDietMealCalories(recipe) : null; const nutrition = nutritionFor(getRecipeNutrition(recipe)); if (dietCalories !== null) nutrition.calories = dietCalories; return { id: `${group}:${recipe.id}`, name: `${recipe.id} · ${recipe.title}`, title: parts.title, subtitle: parts.subtitle, image: getRecipeHeroImage(recipe), nutrition, calories: nutrition.calories, mealBalance: mealBalanceFor(recipe) }; };
    const dinnerSource = (meal, group) => { const parts = titleParts(dinnerTitle(meal, recipeMap), meal.subtitle); const nutrition = nutritionFor(meal); return { id: `${group}:${meal.rfisId || meal.id}`, name: `${meal.rfisId || meal.id} · ${parts.title}`, title: parts.title, subtitle: parts.subtitle, image: getCompleteMealHeroImage(meal), nutrition, calories: nutrition.calories, mealBalance: mealBalanceFor(meal) }; };
    const buildSource = (meal, group) => { const main = recipeMap.get(String(meal.mainId || "").toLowerCase()); const sides = [meal.sideOneId, meal.sideTwoId].map((id) => recipeMap.get(String(id || "").toLowerCase())).filter(Boolean); const parts = titleParts(meal.title || main?.title || "Saved Build-a-Meal", sides.length ? `With ${sides.map((side) => side.title).join(" & ")}` : ""); const nutrition = combineNutrition([main, ...sides].filter(Boolean).map((recipe) => nutritionFor(getRecipeNutrition(recipe)))); if (meal.totalCalories !== null && meal.totalCalories !== undefined) nutrition.calories = meal.totalCalories; return { id: `${group}:${meal.id}`, name: meal.title || parts.title, title: parts.title, subtitle: parts.subtitle, image: main ? getRecipeHeroImage(main) : "", nutrition, calories: nutrition.calories, mealBalance: mealBalanceFor(meal) }; };
    const favoriteIds = new Set(favorites.map(String));
    return {
      complete: completeMeals.map((meal) => dinnerSource(meal, "Complete")),
      healthy: recipes.filter((recipe) => String(recipe.id).toUpperCase().startsWith("DM-")).map((recipe) => recipeSource(recipe, "Healthy")),
      build: savedCustomMeals.map((meal) => buildSource(meal, "Build")), bulk: [],
      favorites: [...recipes.filter((recipe) => favoriteIds.has(String(recipe.id))).map((recipe) => recipeSource(recipe, "Favorite Recipe")), ...completeMeals.filter((meal) => favoriteIds.has(String(meal.id)) || favoriteIds.has(String(meal.rfisId))).map((meal) => dinnerSource(meal, "Favorite Dinner")), ...savedCustomMeals.filter((meal) => meal.favorite).map((meal) => buildSource(meal, "Favorite Build"))],
    };
  }, [completeMeals, favorites, getCompleteMealHeroImage, getDietMealCalories, getRecipeHeroImage, getRecipeNutrition, recipeMap, recipes, savedCustomMeals]);
  const sources = sourceGroups[form.kind] || [], isImage = IMAGE_KINDS.has(form.kind);
  const filteredSources = useMemo(() => { const term = search.trim().toLowerCase(); return (term ? sources.filter((item) => `${item.id} ${item.name}`.toLowerCase().includes(term)) : sources).slice(0, 100); }, [search, sources]);
  const labels = useMemo(() => expandFreezerLabelQueue(saved.queue), [saved.queue]), pages = useMemo(() => arrangeFreezerLabelsForPositions(labels, saved.availablePositions), [labels, saved.availablePositions]);
  useEffect(() => { localStorage.setItem(FREEZER_LABEL_STORAGE_KEY, JSON.stringify(saved)); localStorage.setItem("rrb_has_custom_user_information", "true"); window.dispatchEvent(new CustomEvent("rrb:user-data-changed")); }, [saved]);
  useEffect(() => { const cleanup = () => document.body.classList.remove("printingFreezerLabels"); addEventListener("afterprint", cleanup); return () => { cleanup(); removeEventListener("afterprint", cleanup); }; }, []);
  useEffect(() => { if (!requestedRecipeId) return; const recipe = recipeMap.get(String(requestedRecipeId).toLowerCase()); if (!recipe) { onRequestedRecipeHandled(); return; } const isDietMeal = String(recipe.id || "").toUpperCase().startsWith("DM-"); if (isDietMeal) { const source = sourceGroups.healthy.find((item) => item.id.endsWith(`:${recipe.id}`)); setForm((current) => ({ ...current, kind: "healthy", sourceId: source?.id || "", name: source?.title || recipe.title, subtitle: source?.subtitle || "", image: source?.image || "", nutrition: source?.nutrition || {}, calories: source?.calories ?? "—", mealBalance: source?.mealBalance ?? "—", amount: "1 serving" })); } else { setForm((current) => ({ ...current, kind: "bulk", sourceId: `Recipe:${recipe.id}`, name: recipe.title, subtitle: "", image: "", amount: "1 serving" })); } onRequestedRecipeHandled(); window.scrollTo({ top: 0, behavior: "auto" }); }, [onRequestedRecipeHandled, recipeMap, requestedRecipeId, sourceGroups]);
  function changeKind(kind) { setSearch(""); setForm((current) => ({ ...current, kind, sourceId: "", name: "", subtitle: "", image: "", nutrition: {}, calories: "—", mealBalance: "—", amount: kind === "bulk" ? "1 package" : "1 serving" })); }
  function chooseSource(id) { const source = sources.find((item) => item.id === id); setForm((current) => ({ ...current, sourceId: id, name: source?.title || "", subtitle: source?.subtitle || "", image: source?.image || "", nutrition: source?.nutrition || {}, calories: source?.calories ?? "—", mealBalance: source?.mealBalance ?? "—", amount: "1 serving" })); }
  function addLabel(event) { event.preventDefault(); if (!form.name.trim()) return; const item = { ...form, labelStyle: isImage ? "image" : "text", id: `freezer-label-${Date.now()}`, name: form.name.trim(), copies: Math.min(30, Math.max(1, Number(form.copies) || 1)), createdAt: new Date().toISOString() }; setSaved((current) => ({ ...current, queue: [...current.queue, item] })); setForm(emptyForm()); setSearch(""); }
  function reuseLabel(item) { setForm({ ...emptyForm(), ...item, copies: 1 }); scrollTo({ top: 0, behavior: "smooth" }); }
  function printLabels() { if (!labels.length) return; setSaved((current) => ({ ...current, history: [...current.queue.map((item) => ({ ...item, printedAt: new Date().toISOString() })), ...current.history].slice(0, 100) })); document.body.classList.add("printingFreezerLabels"); setTimeout(() => print(), 50); }
  const pageMarkup = pages.map((page, pageIndex) => <div className="freezerLabelPage" key={pageIndex}>{page.map((label, slotIndex) => label ? <PrintableLabel label={label} key={label.printKey} /> : <div className="freezerLabelBlankSlot" key={`blank-${slotIndex}`}><span>Skipped position {slotIndex + 1}</span></div>)}</div>);
  return <main className="pageShell freezerLabelMakerPage">
    <section className="freezerLabelIntro"><h2>Create Freezer Labels</h2><p>Complete Dinners, Healthy Dinners, and Build-a-Meals use photo labels with per-serving Nutrition Facts. Every portrait letter sheet prints ten 4 × 2-inch labels.</p></section>
    <div className="freezerLabelWorkspace"><form className="freezerLabelForm" onSubmit={addLabel}><h3>1. Label Details</h3><div className="freezerLabelKindTabs" role="tablist" aria-label="Label type">{KINDS.map(([id, label]) => <button type="button" role="tab" aria-selected={form.kind === id} className={form.kind === id ? "active" : ""} onClick={() => changeKind(id)} key={id}>{label}</button>)}</div>
      {form.kind !== "bulk" && <div className="freezerLabelSourcePicker"><label><span>Find a meal</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or code" /></label><label><span>Select</span><select value={form.sourceId} onChange={(event) => chooseSource(event.target.value)}><option value="">Choose from the list…</option>{filteredSources.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></label></div>}
      <label className="freezerLabelWide"><span>{isImage ? "Meal name" : "Food or item name"} *</span><input required value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></label>
      {isImage ? <><label className="freezerLabelWide"><span>With line</span><input value={form.subtitle} onChange={(event) => setForm((current) => ({ ...current, subtitle: event.target.value }))} placeholder="With Mashed Potatoes & Green Beans" /></label><div className="freezerLabelFieldGrid"><label><span>Date</span><input type="date" value={form.frozenDate} onChange={(event) => setForm((current) => ({ ...current, frozenDate: event.target.value }))} /></label><label><span>Number of copies</span><input type="number" min="1" max="30" value={form.copies} onChange={(event) => setForm((current) => ({ ...current, copies: event.target.value }))} /></label></div></> : <><div className="freezerLabelFieldGrid"><label><span>Date frozen</span><input type="date" value={form.frozenDate} onChange={(event) => setForm((current) => ({ ...current, frozenDate: event.target.value }))} /></label><label><span>Use by</span><input type="date" value={form.useByDate} onChange={(event) => setForm((current) => ({ ...current, useByDate: event.target.value }))} /></label><label><span>Quantity</span><input value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} /></label><label><span>Number of copies</span><input type="number" min="1" max="30" value={form.copies} onChange={(event) => setForm((current) => ({ ...current, copies: event.target.value }))} /></label></div><label className="freezerLabelWide"><span>Preparation instructions</span><textarea rows="3" value={form.instructions} onChange={(event) => setForm((current) => ({ ...current, instructions: event.target.value }))} /></label><label className="freezerLabelWide"><span>Optional note</span><input value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))} /></label></>}
      <button className="primary freezerLabelAddButton" type="submit">Add Label to Print Page</button></form>
      <aside className="freezerLabelLivePreview"><h3>Label Preview</h3><PrintableLabel label={{ ...form, labelStyle: isImage ? "image" : "text", name: form.name || (isImage ? "Meal Name" : "Your Freezer Item") }} /><p>{isImage ? "Nutrition Facts are always shown for one serving and are never multiplied by copies or portions." : "Text labels include dates, quantity, preparation instructions, and notes."}</p></aside></div>
    <section className="freezerLabelQueue"><div className="freezerLabelQueueHeader"><div><h3>2. Print Page</h3><p>{labels.length} label{labels.length === 1 ? "" : "s"} ready</p></div><div className="freezerLabelFixedLayout"><span>PORTRAIT LETTER</span><strong>{FREEZER_LABEL_LAYOUTS.portrait.name}</strong></div></div><fieldset className="freezerLabelPositionPicker"><legend>Select the unused labels on your sheet</legend><p>Position 1 is the upper-left label. Clear any positions that have already been used.</p><div className="freezerLabelPositionGrid">{FREEZER_LABEL_POSITIONS.map((position) => <label key={position}><input type="checkbox" checked={saved.availablePositions.includes(position)} onChange={() => setSaved((current) => ({ ...current, availablePositions: current.availablePositions.includes(position) ? current.availablePositions.filter((item) => item !== position) : [...current.availablePositions, position].sort((a, b) => a - b) }))} /><span>{position}</span></label>)}</div><div className="freezerLabelPositionActions"><button type="button" className="secondary" onClick={() => setSaved((current) => ({ ...current, availablePositions: [...FREEZER_LABEL_POSITIONS] }))}>Select All</button><button type="button" className="secondary" onClick={() => setSaved((current) => ({ ...current, availablePositions: [] }))}>Clear All</button><strong>{saved.availablePositions.length} available</strong></div></fieldset>{saved.queue.length ? <div className="freezerLabelQueueList">{saved.queue.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.labelStyle === "image" ? item.subtitle || "Photo label" : `${item.amount} · Frozen ${formatFreezerLabelDate(item.frozenDate)}`} · {item.copies} copies</span></div><button type="button" onClick={() => reuseLabel(item)}>Edit a Copy</button><button type="button" className="danger" onClick={() => setSaved((current) => ({ ...current, queue: current.queue.filter((entry) => entry.id !== item.id) }))}>Remove</button></article>)}</div> : <div className="freezerLabelEmpty">Add a label above to begin building your printable page.</div>}<div className="freezerLabelActions"><button type="button" className="primary" disabled={!labels.length || !saved.availablePositions.length} onClick={() => setShowPreview(true)}>Preview Print Page</button><button type="button" className="secondary" disabled={!labels.length || !saved.availablePositions.length} onClick={printLabels}>Print Labels</button><button type="button" className="secondary" disabled={!saved.queue.length} onClick={() => setSaved((current) => ({ ...current, queue: [] }))}>Clear Page</button></div></section>
    {showPreview && <div className="freezerLabelPreviewBackdrop" role="dialog" aria-modal="true"><section className="freezerLabelPreviewModal"><header><div><h2>Print Preview</h2><p>Use portrait orientation and 100% scale on 4 × 2-inch, 10-up label stock.</p></div><button type="button" onClick={() => setShowPreview(false)}>×</button></header><div className="freezerLabelPreviewPages">{pageMarkup}</div><footer><button type="button" className="primary" onClick={printLabels}>Print These Labels</button><button type="button" className="secondary" onClick={() => setShowPreview(false)}>Close</button></footer></section></div>}
    <div className="freezerLabelPrintRoot" aria-hidden="true">{pageMarkup}</div>
  </main>;
}
