import { useEffect, useMemo, useState } from "react";
import { FREEZER_LABEL_LAYOUTS, FREEZER_LABEL_STORAGE_KEY, addFreezerMonths, expandFreezerLabelQueue, formatFreezerLabelDate, localFreezerLabelDate, normalizeFreezerLabelState, paginateFreezerLabels } from "../utils/freezerLabels.js";
import "./FreezerLabelMaker.css";

const IMAGE_KINDS = new Set(["complete", "healthy", "build", "favorites"]);
const KINDS = [["complete", "Complete Dinners"], ["healthy", "Healthy Dinners"], ["build", "Build-a-Meals"], ["bulk", "Bulk Items"], ["favorites", "Favorites"]];
function emptyForm() { const frozenDate = localFreezerLabelDate(); return { kind: "complete", sourceId: "", name: "", subtitle: "", image: "", frozenDate, useByDate: addFreezerMonths(frozenDate, 3), amount: "1 package", instructions: "", notes: "", copies: 1 }; }
function loadState() { try { return normalizeFreezerLabelState(JSON.parse(localStorage.getItem(FREEZER_LABEL_STORAGE_KEY) || "{}")); } catch { return normalizeFreezerLabelState({}); } }
function titleParts(title = "", subtitle = "") { if (subtitle) return { title, subtitle }; const parts = String(title).split(/\s+with\s+/i); return parts.length > 1 ? { title: parts.shift(), subtitle: `With ${parts.join(" with ")}` } : { title, subtitle: "" }; }
function dinnerTitle(meal, recipeMap) { if (meal.title) return meal.title; return recipeMap.get(String(meal.mainRecipeId || "").toLowerCase())?.title || meal.rfisId || meal.id || "Complete Dinner"; }

function PrintableLabel({ label }) {
  if (label.labelStyle === "image" || IMAGE_KINDS.has(label.kind)) return <article className="freezerPrintableLabel freezerImageLabel">{label.image ? <img src={label.image} alt="" /> : <div className="freezerImagePlaceholder">Meal image</div>}<div className="freezerImageLabelCopy"><h3>{label.name}</h3>{label.subtitle && <p>{label.subtitle}</p>}</div></article>;
  return <article className="freezerPrintableLabel freezerTextLabel"><h3>{label.name}</h3><div className="freezerLabelFacts"><span><small>FROZEN</small><strong>{formatFreezerLabelDate(label.frozenDate)}</strong></span><span><small>USE BY</small><strong>{formatFreezerLabelDate(label.useByDate)}</strong></span><span><small>AMOUNT</small><strong>{label.amount || "—"}</strong></span></div>{label.instructions && <p><strong>PREP:</strong> {label.instructions}</p>}{label.notes && <p><strong>NOTE:</strong> {label.notes}</p>}</article>;
}

export default function FreezerLabelMaker({ recipes = [], completeMeals = [], favorites = [], savedCustomMeals = [], getRecipeHeroImage = () => "", getCompleteMealHeroImage = () => "" }) {
  const [saved, setSaved] = useState(loadState), [form, setForm] = useState(emptyForm), [search, setSearch] = useState(""), [showPreview, setShowPreview] = useState(false);
  const recipeMap = useMemo(() => new Map(recipes.map((recipe) => [String(recipe.id).toLowerCase(), recipe])), [recipes]);
  const sourceGroups = useMemo(() => {
    const recipeSource = (recipe, group) => { const parts = titleParts(recipe.title); return { id: `${group}:${recipe.id}`, name: `${recipe.id} · ${recipe.title}`, title: parts.title, subtitle: parts.subtitle, image: getRecipeHeroImage(recipe) }; };
    const dinnerSource = (meal, group) => { const parts = titleParts(dinnerTitle(meal, recipeMap), meal.subtitle); return { id: `${group}:${meal.rfisId || meal.id}`, name: `${meal.rfisId || meal.id} · ${parts.title}`, title: parts.title, subtitle: parts.subtitle, image: getCompleteMealHeroImage(meal) }; };
    const buildSource = (meal, group) => { const main = recipeMap.get(String(meal.mainId || "").toLowerCase()); const sides = [meal.sideOneId, meal.sideTwoId].map((id) => recipeMap.get(String(id || "").toLowerCase())?.title).filter(Boolean); const parts = titleParts(meal.title || main?.title || "Saved Build-a-Meal", sides.length ? `With ${sides.join(" & ")}` : ""); return { id: `${group}:${meal.id}`, name: meal.title || parts.title, title: parts.title, subtitle: parts.subtitle, image: main ? getRecipeHeroImage(main) : "" }; };
    const favoriteIds = new Set(favorites.map(String));
    return {
      complete: completeMeals.map((meal) => dinnerSource(meal, "Complete")),
      healthy: recipes.filter((recipe) => String(recipe.id).toUpperCase().startsWith("DM-")).map((recipe) => recipeSource(recipe, "Healthy")),
      build: savedCustomMeals.map((meal) => buildSource(meal, "Build")), bulk: [],
      favorites: [...recipes.filter((recipe) => favoriteIds.has(String(recipe.id))).map((recipe) => recipeSource(recipe, "Favorite Recipe")), ...completeMeals.filter((meal) => favoriteIds.has(String(meal.id)) || favoriteIds.has(String(meal.rfisId))).map((meal) => dinnerSource(meal, "Favorite Dinner")), ...savedCustomMeals.filter((meal) => meal.favorite).map((meal) => buildSource(meal, "Favorite Build"))],
    };
  }, [completeMeals, favorites, getCompleteMealHeroImage, getRecipeHeroImage, recipeMap, recipes, savedCustomMeals]);
  const sources = sourceGroups[form.kind] || [], isImage = IMAGE_KINDS.has(form.kind);
  const filteredSources = useMemo(() => { const term = search.trim().toLowerCase(); return (term ? sources.filter((item) => `${item.id} ${item.name}`.toLowerCase().includes(term)) : sources).slice(0, 100); }, [search, sources]);
  const labels = useMemo(() => expandFreezerLabelQueue(saved.queue), [saved.queue]), pages = useMemo(() => paginateFreezerLabels(labels), [labels]);
  useEffect(() => { localStorage.setItem(FREEZER_LABEL_STORAGE_KEY, JSON.stringify(saved)); localStorage.setItem("rrb_has_custom_user_information", "true"); window.dispatchEvent(new CustomEvent("rrb:user-data-changed")); }, [saved]);
  useEffect(() => { const cleanup = () => document.body.classList.remove("printingFreezerLabels"); addEventListener("afterprint", cleanup); return () => { cleanup(); removeEventListener("afterprint", cleanup); }; }, []);
  function changeKind(kind) { setSearch(""); setForm((current) => ({ ...current, kind, sourceId: "", name: "", subtitle: "", image: "" })); }
  function chooseSource(id) { const source = sources.find((item) => item.id === id); setForm((current) => ({ ...current, sourceId: id, name: source?.title || "", subtitle: source?.subtitle || "", image: source?.image || "" })); }
  function addLabel(event) { event.preventDefault(); if (!form.name.trim()) return; const item = { ...form, labelStyle: isImage ? "image" : "text", id: `freezer-label-${Date.now()}`, name: form.name.trim(), copies: Math.min(30, Math.max(1, Number(form.copies) || 1)), createdAt: new Date().toISOString() }; setSaved((current) => ({ ...current, queue: [...current.queue, item] })); setForm(emptyForm()); setSearch(""); }
  function reuseLabel(item) { setForm({ ...emptyForm(), ...item, copies: 1 }); scrollTo({ top: 0, behavior: "smooth" }); }
  function printLabels() { if (!labels.length) return; setSaved((current) => ({ ...current, history: [...current.queue.map((item) => ({ ...item, printedAt: new Date().toISOString() })), ...current.history].slice(0, 100) })); document.body.classList.add("printingFreezerLabels"); setTimeout(() => print(), 50); }
  const pageMarkup = pages.map((page, pageIndex) => <div className="freezerLabelPage" key={pageIndex}>{page.map((label) => <PrintableLabel label={label} key={label.printKey} />)}</div>);
  return <main className="pageShell freezerLabelMakerPage">
    <section className="freezerLabelIntro"><h2>Create Freezer Labels</h2><p>Choose a meal collection for a photo label, or use Bulk Items for a detailed text label. Every landscape letter sheet prints four 4.25 × 3.5-inch labels.</p></section>
    <div className="freezerLabelWorkspace"><form className="freezerLabelForm" onSubmit={addLabel}><h3>1. Label Details</h3><div className="freezerLabelKindTabs" role="tablist" aria-label="Label type">{KINDS.map(([id, label]) => <button type="button" role="tab" aria-selected={form.kind === id} className={form.kind === id ? "active" : ""} onClick={() => changeKind(id)} key={id}>{label}</button>)}</div>
      {form.kind !== "bulk" && <div className="freezerLabelSourcePicker"><label><span>Find a meal</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or code" /></label><label><span>Select</span><select value={form.sourceId} onChange={(event) => chooseSource(event.target.value)}><option value="">Choose from the list…</option>{filteredSources.map((source) => <option value={source.id} key={source.id}>{source.name}</option>)}</select></label></div>}
      <label className="freezerLabelWide"><span>{isImage ? "Meal name" : "Food or item name"} *</span><input required value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} /></label>
      {isImage ? <><label className="freezerLabelWide"><span>With line</span><input value={form.subtitle} onChange={(event) => setForm((current) => ({ ...current, subtitle: event.target.value }))} placeholder="With Mashed Potatoes & Green Beans" /></label><label><span>Number of copies</span><input type="number" min="1" max="30" value={form.copies} onChange={(event) => setForm((current) => ({ ...current, copies: event.target.value }))} /></label></> : <><div className="freezerLabelFieldGrid"><label><span>Date frozen</span><input type="date" value={form.frozenDate} onChange={(event) => setForm((current) => ({ ...current, frozenDate: event.target.value }))} /></label><label><span>Use by</span><input type="date" value={form.useByDate} onChange={(event) => setForm((current) => ({ ...current, useByDate: event.target.value }))} /></label><label><span>Quantity</span><input value={form.amount} onChange={(event) => setForm((current) => ({ ...current, amount: event.target.value }))} /></label><label><span>Number of copies</span><input type="number" min="1" max="30" value={form.copies} onChange={(event) => setForm((current) => ({ ...current, copies: event.target.value }))} /></label></div><label className="freezerLabelWide"><span>Preparation instructions</span><textarea rows="3" value={form.instructions} onChange={(event) => setForm((current) => ({ ...current, instructions: event.target.value }))} /></label><label className="freezerLabelWide"><span>Optional note</span><input value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value }))} /></label></>}
      <button className="primary freezerLabelAddButton" type="submit">Add Label to Print Page</button></form>
      <aside className="freezerLabelLivePreview"><h3>Label Preview</h3><PrintableLabel label={{ ...form, labelStyle: isImage ? "image" : "text", name: form.name || (isImage ? "Meal Name" : "Your Freezer Item") }} /><p>{isImage ? "Photo labels show only the centered hero image, meal name, and With line." : "Text labels include dates, quantity, preparation instructions, and notes."}</p></aside></div>
    <section className="freezerLabelQueue"><div className="freezerLabelQueueHeader"><div><h3>2. Print Page</h3><p>{labels.length} label{labels.length === 1 ? "" : "s"} ready</p></div><div className="freezerLabelFixedLayout"><span>LANDSCAPE LETTER</span><strong>{FREEZER_LABEL_LAYOUTS.landscape.name}</strong></div></div>{saved.queue.length ? <div className="freezerLabelQueueList">{saved.queue.map((item) => <article key={item.id}><div><strong>{item.name}</strong><span>{item.labelStyle === "image" ? item.subtitle || "Photo label" : `${item.amount} · Frozen ${formatFreezerLabelDate(item.frozenDate)}`} · {item.copies} copies</span></div><button type="button" onClick={() => reuseLabel(item)}>Edit a Copy</button><button type="button" className="danger" onClick={() => setSaved((current) => ({ ...current, queue: current.queue.filter((entry) => entry.id !== item.id) }))}>Remove</button></article>)}</div> : <div className="freezerLabelEmpty">Add a label above to begin building your printable page.</div>}<div className="freezerLabelActions"><button type="button" className="primary" disabled={!labels.length} onClick={() => setShowPreview(true)}>Preview Print Page</button><button type="button" className="secondary" disabled={!labels.length} onClick={printLabels}>Print Labels</button><button type="button" className="secondary" disabled={!saved.queue.length} onClick={() => setSaved((current) => ({ ...current, queue: [] }))}>Clear Page</button></div></section>
    {showPreview && <div className="freezerLabelPreviewBackdrop" role="dialog" aria-modal="true"><section className="freezerLabelPreviewModal"><header><div><h2>Print Preview</h2><p>Use landscape orientation and 100% scale. Cut around each border.</p></div><button type="button" onClick={() => setShowPreview(false)}>×</button></header><div className="freezerLabelPreviewPages">{pageMarkup}</div><footer><button type="button" className="primary" onClick={printLabels}>Print These Labels</button><button type="button" className="secondary" onClick={() => setShowPreview(false)}>Close</button></footer></section></div>}
    <div className="freezerLabelPrintRoot" aria-hidden="true">{pageMarkup}</div>
  </main>;
}
