export const FREEZER_LABEL_STORAGE_KEY = "rrb_freezerLabelMaker_v1";
export const FREEZER_LABEL_LAYOUTS = Object.freeze({ portrait: { id: "portrait", name: "10 labels · 4 × 2 inches", columns: 2, rows: 5 } });
export const FREEZER_LABEL_POSITIONS = Object.freeze(Array.from({ length: 10 }, (_, index) => index + 1));
export function localFreezerLabelDate(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
export function addFreezerMonths(value, months = 3) { const parts = String(value || "").match(/^(\d{4})-(\d{2})-(\d{2})$/); if (!parts) return ""; const date = new Date(Number(parts[1]), Number(parts[2]) - 1, Number(parts[3])); date.setMonth(date.getMonth() + Number(months || 0)); return localFreezerLabelDate(date); }
export function formatFreezerLabelDate(value) { const parts = String(value || "").match(/^(\d{4})-(\d{2})-(\d{2})$/); return parts ? `${Number(parts[2])}/${Number(parts[3])}/${parts[1]}` : "—"; }
export function normalizeFreezerLabelState(value) { const source = value && typeof value === "object" ? value : {}; const positions = Array.isArray(source.availablePositions) ? source.availablePositions.map(Number).filter((position) => FREEZER_LABEL_POSITIONS.includes(position)) : FREEZER_LABEL_POSITIONS; return { layout: "portrait", availablePositions: [...new Set(positions)].sort((a, b) => a - b), queue: Array.isArray(source.queue) ? source.queue.filter((item) => item?.id && item?.name).slice(0, 120) : [], history: Array.isArray(source.history) ? source.history.filter((item) => item?.id && item?.name).slice(0, 100) : [] }; }
export function expandFreezerLabelQueue(queue = []) { return queue.flatMap((label) => Array.from({ length: Math.min(30, Math.max(1, Math.floor(Number(label.copies) || 1))) }, (_, index) => ({ ...label, printKey: `${label.id}-${index}` }))); }
export function paginateFreezerLabels(labels = []) { return Array.from({ length: Math.ceil(labels.length / 10) }, (_, page) => labels.slice(page * 10, (page + 1) * 10)); }
export function arrangeFreezerLabelsForPositions(labels = [], positions = FREEZER_LABEL_POSITIONS) { const available = [...new Set(positions.map(Number).filter((position) => FREEZER_LABEL_POSITIONS.includes(position)))].sort((a, b) => a - b); if (!available.length || !labels.length) return []; return Array.from({ length: Math.ceil(labels.length / available.length) }, (_, pageIndex) => { const page = Array(10).fill(null); labels.slice(pageIndex * available.length, (pageIndex + 1) * available.length).forEach((label, index) => { page[available[index] - 1] = label; }); return page; }); }
