import { recipeOverrides as permanentRecipeOverrides } from "../data/recipeOverrides.js";

export const RECIPE_OVERRIDE_STORAGE_KEY = "rrb_recipe_overrides_v1";

export function loadBrowserRecipeOverrides() {
  if (typeof window === "undefined") return {};
  try {
    const parsed = JSON.parse(window.localStorage.getItem(RECIPE_OVERRIDE_STORAGE_KEY) || "{}");
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {};
  } catch {
    return {};
  }
}

export function loadCombinedRecipeOverrides() {
  return { ...permanentRecipeOverrides, ...loadBrowserRecipeOverrides() };
}

export function applyStoredRecipeOverrides(recipes = []) {
  const overrides = loadCombinedRecipeOverrides();
  return recipes.map((recipe) => {
    const merged = { ...recipe, ...(overrides[recipe.id] || {}) };
    return String(merged.id || "").toUpperCase().startsWith("CP-")
      ? { ...merged, servings: 6 }
      : merged;
  });
}

export function saveBrowserRecipeOverrides(overrides) {
  window.localStorage.setItem(RECIPE_OVERRIDE_STORAGE_KEY, JSON.stringify(overrides));
}

export function exportRecipeOverrides(overrides) {
  const source = `// Generated by Robert's Recipe Box Admin Recipe Editor.\nexport const recipeOverrides = ${JSON.stringify(overrides, null, 2)};\n`;
  const blob = new Blob([source], { type: "text/javascript;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = "recipeOverrides.updated.js";
  anchor.click();
  URL.revokeObjectURL(url);
}
